version: '3'

services:
  stretch-shib-idp-test01:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
         - "8080:8080"
         - "8443:8443"
    networks:
        idp-network:
          aliases:
            - shib-idp
    volumes:
      - /var/tmp/docker-logs-jetty:/opt/jetty/logs
      - /var/tmp/docker-logs-shibboleth:/opt/shibboleth-idp/logs

  mysql-idp:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: example
    networks:
        idp-network:
          aliases:
            - idp-db
    volumes:
        - db_data:/var/lib/mysql
volumes:
  db_data:
networks:
  idp-network:
